// Generated by CoffeeScript 1.3.1
(function() {
  var MaPlot, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  MaPlot = function() {
    var brush, brushEnd, brushOn, brushStart, chart, color, display_selected, g, height, margin, points, radius, selected_display_element, width, xAxis, xDomain, xScale, xValue, yAxis, yDomain, yScale, yValue;
    width = 600;
    height = 600;
    margin = {
      top: 20,
      right: 20,
      bottom: 20,
      left: 40
    };
    xValue = function(d) {
      return parseFloat(d.a);
    };
    yValue = function(d) {
      return parseFloat(d.m);
    };
    radius = 3;
    color = function(d) {
      if (yValue(d) > 0) {
        return "#000";
      } else {
        return "#ccc";
      }
    };
    selected_display_element = "#table_display";
    g = null;
    points = null;
    xScale = d3.scale.linear().range([0, width]);
    yScale = d3.scale.linear().range([0, height]);
    xDomain = function(data) {
      return d3.extent(data, xValue);
    };
    yDomain = function(data) {
      return d3.extent(data, yValue).reverse();
    };
    xAxis = d3.svg.axis().scale(xScale).orient("bottom");
    yAxis = d3.svg.axis().scale(yScale).orient("left");
    brushStart = function(p) {
      if (brush.empty()) {
        points.call(brush.clear());
        return points.selectAll("circle").attr("fill", color);
      }
    };
    brushOn = function(p) {
      var all_points, e, selected_points;
      e = brush.extent();
      all_points = points.selectAll("circle");
      selected_points = all_points.filter(function(d) {
        if (e[0][0] <= xValue(d) && xValue(d) <= e[1][0] && e[0][1] <= yValue(d) && yValue(d) <= e[1][1]) {
          return true;
        } else {
          return false;
        }
      });
      all_points.attr("fill", color);
      selected_points.attr("fill", "blue");
      return display_selected(selected_points);
    };
    brushEnd = function(p) {
      if (brush.empty()) {
        return points.selectAll("circle").attr("fill", color);
      }
    };
    brush = d3.svg.brush().on("brushstart", brushStart).on("brush", brushOn).on("brushend", brushEnd);
    chart = function(selection) {
      return selection.each(function(data) {
        var gEnter, svg;
        xScale.domain(xDomain(data));
        yScale.domain(yDomain(data));
        brush.x(xScale).y(yScale);
        svg = d3.select(this).selectAll("svg").data([data]);
        gEnter = svg.enter().append("svg").append("g");
        svg.attr("width", width + margin.left + margin.right);
        svg.attr("height", height + margin.top + margin.bottom);
        g = svg.select("g").attr("transform", "translate(" + margin.left + "," + margin.top + ")");
        g.append("g").attr("class", "x axis").attr("transform", "translate(" + 0 + "," + height + ")").call(xAxis);
        g.append("g").attr("class", "y axis").attr("transform", "translate(" + 0 + "," + 0 + ")").call(yAxis);
        points = g.append("g").attr("class", "points");
        points.selectAll("circle").data(data).enter().append("circle").attr("class", "point").attr("cx", function(d) {
          return xScale(xValue(d));
        }).attr("cy", function(d) {
          return yScale(yValue(d));
        }).attr("r", radius).attr("fill", color);
        return points.call(brush);
      });
    };
    display_selected = function(selected_points) {
      var selection, ss;
      ss = [];
      selected_points.each(function(d) {
        return ss.push(d);
      });
      selection = d3.select(selected_display_element).selectAll("p").data(ss, function(d) {
        return d.index;
      });
      selection.exit().remove();
      return selection.enter().append("p").html(function(d, i) {
        return "" + i + " - " + d.index;
      });
    };
    chart.height = function(_) {
      if (!arguments.length) {
        return height;
      }
      height = _;
      return chart;
    };
    chart.width = function(_) {
      if (!arguments.length) {
        return width;
      }
      width = _;
      return chart;
    };
    chart.margin = function(_) {
      if (!arguments.length) {
        return margin;
      }
      margin = _;
      return chart;
    };
    chart.radius = function(_) {
      if (!arguments.length) {
        return radius;
      }
      radius = _;
      return chart;
    };
    chart.color = function(_) {
      if (!arguments.length) {
        return color;
      }
      color = _;
      return chart;
    };
    chart.x = function(_) {
      if (!arguments.length) {
        return xValue;
      }
      xValue = _;
      return chart;
    };
    chart.y = function(_) {
      if (!arguments.length) {
        return yValue;
      }
      yValue = _;
      return chart;
    };
    return chart;
  };

  root.MaPlot = MaPlot;

}).call(this);
