// Generated by CoffeeScript 1.3.1
(function() {
  var Plot, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  Plot = function() {
    var chart, height, margin, width, xValue, yValue;
    width = 600;
    height = 600;
    margin = {
      top: 20,
      right: 20,
      bottom: 20,
      left: 20
    };
    xValue = function(d) {
      return parseFloat(d.x);
    };
    yValue = function(d) {
      return parseFloat(d.y);
    };
    chart = function(selection) {
      return selection.each(function(data) {
        var g, gEnter, svg;
        console.log("chart");
        svg = d3.select(this).selectAll("svg").data([data]);
        gEnter = svg.enter().append("svg").append("g");
        svg.attr("width", width + margin.left + margin.right);
        svg.attr("height", height + margin.top + margin.bottom);
        return g = svg.select("g").attr("transform", "translate(" + margin.left + "," + margin.top + ")");
      });
    };
    chart.height = function(_) {
      if (!arguments.length) {
        return height;
      }
      height = _;
      return chart;
    };
    chart.width = function(_) {
      if (!arguments.length) {
        return width;
      }
      width = _;
      return chart;
    };
    chart.margin = function(_) {
      if (!arguments.length) {
        return margin;
      }
      margin = _;
      return chart;
    };
    chart.x = function(_) {
      if (!arguments.length) {
        return xValue;
      }
      xValue = _;
      return chart;
    };
    chart.y = function(_) {
      if (!arguments.length) {
        return yValue;
      }
      yValue = _;
      return chart;
    };
    return chart;
  };

  root.Plot = Plot;

}).call(this);
